CREATE DATABASE customer_behavior;

SHOW DATABASES;

USE customer_behavior;

SELECT * 
FROM customers
LIMIT 10;

-- 1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customers
GROUP BY(gender);

-- 2. Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customers)  ;

-- 3. Which are the top 5 products with hightest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) as "average product rating"
FROM customers
GROUP BY(item_purchased)
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4. Compare the Average Purchase amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) as "Average Purchase Amount"
FROM customers
GROUP BY shipping_type 
HAVING shipping_type in ('Express', 'Standard');

-- 5. Do Subscribed users spend more? Compare average spend and Total Revenue between Subscribers and Non-Subscribers.
SELECT subscription_status, COUNT(customer_id), ROUND(AVG(purchase_amount),2) as average_spend , ROUND(SUM(purchase_amount),2) as total_revenue
FROM customers
GROUP BY(subscription_status)
ORDER BY average_spend, total_revenue;

-- 6. Which 5 products have highest percentage of purchased with discounts applied?
SELECT item_purchased, ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as "Percentage_of_Purchase" 
FROM customers
GROUP BY item_purchased
ORDER BY Percentage_of_Purchase desc
LIMIT 5;

-- 7. Segment customers into New, Returning and Loyal based on their previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN "New"
    WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
    ELSE "Loyal"
    END as customer_segment
from customers
)
SELECT customer_segment, COUNT(*) as "No_of_Customers"
FROM customer_type
GROUP BY customer_segment;

-- What are the top 3 most purchased products within each category?
with item_counts as(
SELECT category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customers
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. What is the revenue contibution of each age group?
SELECT age_group, SUM(purchase_amount) as total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;

